// <auto-generated />
using KomgrichApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace KomgrichApi.Migrations
{
    [DbContext(typeof(SchoolContext))]
    partial class SchoolContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("KomgrichApi.Models.Students", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("degree")
                        .HasColumnType("text");

                    b.Property<string>("fullname")
                        .HasColumnType("text");

                    b.Property<string>("student_id")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("KomgrichApi.Models.StudentsUniversities", b =>
                {
                    b.Property<long>("StudentId")
                        .HasColumnType("bigint");

                    b.Property<long>("UniversitieId")
                        .HasColumnType("bigint");

                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.HasKey("StudentId", "UniversitieId");

                    b.HasIndex("UniversitieId");

                    b.ToTable("StudentsUniversities");
                });

            modelBuilder.Entity("KomgrichApi.Models.universities", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("university_name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("universities");
                });

            modelBuilder.Entity("KomgrichApi.Models.StudentsUniversities", b =>
                {
                    b.HasOne("KomgrichApi.Models.Students", "Student")
                        .WithMany("StudentsUniversitie")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KomgrichApi.Models.universities", "universitie")
                        .WithMany("StudentsUniversitie")
                        .HasForeignKey("UniversitieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("universitie");
                });

            modelBuilder.Entity("KomgrichApi.Models.Students", b =>
                {
                    b.Navigation("StudentsUniversitie");
                });

            modelBuilder.Entity("KomgrichApi.Models.universities", b =>
                {
                    b.Navigation("StudentsUniversitie");
                });
#pragma warning restore 612, 618
        }
    }
}
